import { readdir, readFile, writeFile } from "node:fs/promises";
import matter from "gray-matter";

const contentRoot = new URL("../content/", import.meta.url);
const outputFile = new URL("posts.generated.ts", contentRoot);
const sections = ["research", "blog"];

function requireText(value, field, fileName) {
  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`${fileName}: ${field} must be a non-empty string`);
  }

  return value.trim();
}

function optionalTextList(value, field, fileName) {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`${fileName}: ${field} must be a list of strings`);
  }

  return value;
}

function optionalLinks(value, fileName) {
  if (value === undefined) return undefined;
  if (
    !Array.isArray(value) ||
    value.some(
      (link) =>
        !link ||
        typeof link !== "object" ||
        typeof link.label !== "string" ||
        !link.label.trim() ||
        typeof link.href !== "string" ||
        !link.href.trim(),
    )
  ) {
    throw new Error(`${fileName}: links must contain label and href values`);
  }

  return value.map((link) => ({ label: link.label.trim(), href: link.href.trim() }));
}

function formatDate(date, fileName) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new Error(`${fileName}: date must use YYYY-MM-DD`);
  }

  const parsed = new Date(`${date}T00:00:00Z`);
  if (Number.isNaN(parsed.valueOf())) {
    throw new Error(`${fileName}: date is invalid`);
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
    timeZone: "UTC",
  }).format(parsed);
}

async function readSection(kind) {
  const directory = new URL(`${kind}/`, contentRoot);
  const entries = await readdir(directory, { withFileTypes: true });
  const markdownFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md") && !entry.name.startsWith("_"))
    .map((entry) => entry.name)
    .sort();

  return Promise.all(
    markdownFiles.map(async (fileName) => {
      const file = new URL(fileName, directory);
      const source = await readFile(file, "utf8");
      const { data, content } = matter(source);
      const slug = fileName.slice(0, -3);

      if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
        throw new Error(`${fileName}: filename must use lowercase words separated by hyphens`);
      }

      const date = requireText(data.date, "date", fileName);
      const post = {
        slug,
        kind,
        date,
        displayDate: formatDate(date, fileName),
        title: requireText(data.title, "title", fileName),
        summary: requireText(data.summary, "summary", fileName),
        tags: optionalTextList(data.tags, "tags", fileName),
        links: optionalLinks(data.links, fileName),
        body: content.trim(),
      };

      if (!post.body) {
        throw new Error(`${fileName}: article body cannot be empty`);
      }

      if (!post.links) delete post.links;
      return post;
    }),
  );
}

const posts = (await Promise.all(sections.map(readSection))).flat();
const duplicateSlugs = posts
  .map((post) => post.slug)
  .filter((slug, index, slugs) => slugs.indexOf(slug) !== index);

if (duplicateSlugs.length > 0) {
  throw new Error(`Duplicate article slug: ${[...new Set(duplicateSlugs)].join(", ")}`);
}

const generated = `// This file is generated by scripts/generate-posts.mjs. Do not edit it.\nimport type { Post } from "./post-types";\n\nexport const generatedPosts = ${JSON.stringify(posts, null, 2)} satisfies Post[];\n`;

let existing = "";
try {
  existing = await readFile(outputFile, "utf8");
} catch {
  // The generated file does not exist on a fresh checkout.
}

if (existing !== generated) {
  await writeFile(outputFile, generated);
}

console.log(`Generated ${posts.length} posts from individual Markdown files.`);
